# 2次元上の結果を3次元で統合

In [7]:
import cv2
import numpy as np
from tqdm import tqdm

In [45]:
img_num = 670

input_file_down    = "Output/Spectral_sys/12_junk-del-label-inte-sp/ORA-{0:03d}_k-means-200_junk-del-label-inte_sp.png".format(img_num-10)
input_file_current = "Output/Spectral_sys/12_junk-del-label-inte-sp/ORA-{0:03d}_k-means-200_junk-del-label-inte_sp.png".format(img_num)
input_file_up      = "Output/Spectral_sys/12_junk-del-label-inte-sp/ORA-{0:03d}_k-means-200_junk-del-label-inte_sp.png".format(img_num+9)

img_d = cv2.imread(input_file_down)
img_c = cv2.imread(input_file_current)
img_u = cv2.imread(input_file_up)

height,width,color = img_c.shape

color_code_d = np.zeros((100,3))
color_code_c = np.zeros((100,3))
color_code_u = np.zeros((100,3))

temp_d = np.zeros((height,width))
temp_c = np.zeros((height,width))
temp_u = np.zeros((height,width))

In [46]:
img_d_rmb = np.zeros((height,width))
img_c_rmb = np.zeros((height,width))
img_u_rmb = np.zeros((height,width))

for y in tqdm(range(height)):
    for x in range(width):
        if((img_c[y,x,0]== img_c[y,x,1]) and (img_c[y,x,1] == img_c[y,x,2])):
            img_c[y,x] == (0,0,0)
        else:
            img_c_rmb[y,x]=255
            
for y in tqdm(range(height)):
    for x in range(width):
        if((img_d[y,x,0]== img_d[y,x,1]) and (img_d[y,x,1] == img_d[y,x,2])):
            img_d[y,x] == (0,0,0)
        else:
            img_d_rmb[y,x]=255
            
for y in tqdm(range(height)):
    for x in range(width):
        if((img_u[y,x,0]== img_u[y,x,1]) and (img_u[y,x,1] == img_u[y,x,2])):
            img_u[y,x] == (0,0,0)
        else:
            img_u_rmb[y,x]=255

100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 858/858 [00:04<00:00, 174.70it/s]


In [47]:
#img_c_gray = cv2.imread(input_file_current,0)

i = 1

for y in tqdm(range(height)):
    for x in range(width):
        if(img_c_rmb[y,x]==255):
            if(i==1):
                color_code_c[i] = img_c[y,x]
                temp_c[y,x] = i
                i+=1
            else:
                flag = 0
                j = 1

                while(flag != 1 and j <= i):
                    if((color_code_c[j]==img_c[y,x]).all()):
                        flag = 1
                        temp_c[y,x] = j
                    else:
                        j += 1

                if(flag == 0):
                    color_code_c[i] = img_c[y,x]
                    temp_c[y,x] = i
                    i += 1
                    
i = 1

for y in tqdm(range(height)):
    for x in range(width):
        if(img_d_rmb[y,x]==255):
            if(i==1):
                color_code_d[i] = img_d[y,x]
                temp_d[y,x] = i
                i+=1
            else:
                flag = 0
                j = 1

                while(flag != 1 and j <= i):
                    if((color_code_d[j]==img_d[y,x]).all()):
                        flag = 1
                        temp_d[y,x] = j
                    else:
                        j += 1

                if(flag == 0):
                    color_code_d[i] = img_d[y,x]
                    temp_d[y,x] = i
                    i += 1
                    
i = 1

for y in tqdm(range(height)):
    for x in range(width):
        if(img_u_rmb[y,x]==255):
            if(i==1):
                color_code_u[i] = img_u[y,x]
                temp_u[y,x] = i
                i+=1
            else:
                flag = 0
                j = 1

                while(flag != 1 and j <= i):
                    if((color_code_u[j]==img_u[y,x]).all()):
                        flag = 1
                        temp_u[y,x] = j
                    else:
                        j += 1

                if(flag == 0):
                    color_code_u[i] = img_u[y,x]
                    temp_u[y,x] = i
                    i += 1

100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 858/858 [00:06<00:00, 136.31it/s]


In [48]:
ch_num_u = np.zeros((100,100))

for y in tqdm(range(height)):
    for x in range(width):
        if(img_c_rmb[y,x]==255):
            for y_n in range(y-1,y+2):
                for x_n in range(x-1,x+2):
                    if(img_u_rmb[y_n,x_n]==255):
                        ch_num_u[int(temp_u[y_n,x_n]),int(temp_c[y,x])] += 1        

100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 858/858 [00:01<00:00, 827.73it/s]


In [33]:
print(temp_c)

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [49]:
ch_num_u_result = np.zeros(100)

for i in tqdm(range(100)):
    ch_num_axis = ch_num_u[i,:]
    ch_num_u_result[i] = np.argmax(ch_num_axis)

print(ch_num_u_result)

100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 100/100 [00:00<00:00, 60804.64it/s]

[ 0.  1.  3.  4.  7.  5.  6.  7.  8.  7. 10.  5.  0. 11. 19. 16. 23. 13.
 17.  5. 18. 20. 21.  0. 22. 25. 26. 27. 28. 29.  0.  0.  0.  0. 30.  0.
 33. 31. 32. 34. 35. 36. 35.  0. 38. 37.  0.  0.  0.  0.  0.  0.  0.  0.
  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.
  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]


In [50]:
for y in tqdm(range(height)):
    for x in range(width):
        if(img_u_rmb[y,x]==255):
            if(ch_num_u_result[int(temp_u[y,x])] != 0):
                img_u[y,x] = color_code_c[int(ch_num_u_result[int(temp_u[y,x])])]
                
cv2.imwrite('test_3d_2.png',img_u)

100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 858/858 [00:00<00:00, 1569.00it/s]


True